title: Virohin's Awesome Blog
author: Virohin Shakelli
email: vdshakelli@ebnet.org
description: This blog includes facts and events about my life. It will be updated once a month. Enjoy. 

# social links
twitter_username: PhilRogers81
github_username: vshakelli
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
